import numpy as np
import sys
from PyQt4 import QtCore
from PyQt4 import QtGui
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
from matplotlib.backends.backend_qt4 import NavigationToolbar2QT as NavigationToolbar



# import the MainWindow widget from the converted .ui files
from ArchaeoPY.GUI.mpl import Ui_MainWindow

#import ArchaeoPY modules
#import stats
class ArchaeoPYMainWindow(QtGui.QMainWindow, Ui_MainWindow):

        
        """Customization for Qt Designer created window"""
    
        def ClearPlot(self):
            self.mpl.canvas.ax.clear()
            self.mpl.canvas.draw()
            
        def copy_to_clipboard(self):
            pixmap = QtGui.QPixmap.grabWidget(self.mpl.canvas)
            QtGui.QApplication.clipboard().setPixmap(pixmap)
            
        def Open_File(self):
            self.fname = QtGui.QFileDialog.getOpenFileName()
        '''
        def Save_Stats(self):
            self.f = open(self.fname, 'rb')
            data = np.genfromtxt(self.f, skip_header=1)
            fname = QtGui.QFileDialog.getSaveFileName(self, 'Save File', 
               '*.csv')            
            output_text = np.column_stack((self.x,self.y))
            np.savetxt(str(fname),output_text,fmt ='%1.2f',delimiter=',', header = self.header)                        
'''
        def Plot_Function(self):
            self.f = open(self.fname, 'rb')
            data = np.genfromtxt(self.fname, skip_header=1)
            x = [':,0', ':,1', ':,2', ':,3', ':,4', ':,5', ':,6', ':,7', ':,8']
            x_colm = x[self.xcombo.currentIndex()]
            if x_colm == ':,0':
                self.x = data[:,0]
            if x_colm == ':,1':
                self.x = data[:,1]
            if x_colm == ':,2':
                self.x = data[:,2]            
            if x_colm == ':,3':
                self.x = data[:,3]
            if x_colm == ':,4':
                self.x = data[:,4]
            if x_colm == ':,5':
                self.x = data[:,5]
            if x_colm == ':,6':
                self.x = data[:,6]
            if x_colm == ':,7':
                self.x = data[:,7]
            if x_colm == ':,8':
                self.x = data[:,8]
            y = [':,0', ':,1', ':,2', ':,3', ':,4', ':,5', ':,6', ':,7', ':,8']
            y_colm = y[self.ycombo.currentIndex()]
            if y_colm == ':,0':
                self.y = data[:,0]
            if y_colm == ':,1':
                self.y = data[:,1]
            if y_colm == ':,2':
                self.y = data[:,2]            
            if y_colm == ':,3':
                self.y = data[:,3]
            if y_colm == ':,4':
                self.y = data[:,4]
            if y_colm == ':,5':
                self.y = data[:,5]
            if y_colm == ':,6':
                self.y = data[:,6]
            if y_colm == ':,7':
                self.y = data[:,7]
            if y_colm == ':,8':
                self.y = data[:,8]
            self.mpl.canvas.ax.scatter(self.x,self.y)
            self.mpl.canvas.ax.axis('auto')
            #self.mpl.canvas.ax.set_xlim(xmin=np.min(self.x), xmax=(np.max(self.x)))
            self.mpl.canvas.ax.set_ylim(ymin=np.min(self.y), ymax=(np.max(self.y)))
            self.mpl.canvas.ax.set_autoscale_on(True)
            self.mpl.canvas.ax.autoscale_view(True,True,True)
            #self.mpl.canvas.ax.set_xlabel(self.xtitle, size = 15)
            #self.mpl.canvas.ax.set_ylabel(self.ytitle, size = 15)
            #self.mpl.canvas.ax.set_title(self.title, size = 15)
            self.mpl.canvas.draw()
        
                        
        def Button_Definitions(self):
            self.firstrun=True
            
            self.Open_button = QtGui.QPushButton('Open', self)
            self.fname = self.Open_button.clicked.connect(self.Open_File)
            self.fname = self.Open_button.clicked.connect(self.Plot_Function)
            self.Button_Layout.addWidget(self.Open_button)
            
            self.pushButton_plot.clicked.connect(self.Plot_Function)
            self.pushButton_clear.clicked.connect(self.ClearPlot)
            QtGui.QShortcut(QtGui.QKeySequence("Ctrl+P"),self, self.Plot_Function)
                    
        def __init__(self, parent = None):
            # initialization of the superclass
            super(ArchaeoPYMainWindow, self).__init__(parent)
            # setup the GUI --> function generated by pyuic4
            self.setupUi(self)
            #Adds a Matplotlib Toolbar to the display, clears the display and adds only the required buttons
            self.navi_toolbar = NavigationToolbar(self.mpl.canvas, self)
            self.navi_toolbar.clear()
    
        #Adds Buttons
            a = self.navi_toolbar.addAction(self.navi_toolbar._icon('home.png'), 'Home',
                                            self.navi_toolbar.home)
            #a.setToolTip('returns axes to original position')
            a = self.navi_toolbar.addAction(self.navi_toolbar._icon('move.png'), 'Pan',
                                            self.navi_toolbar.pan)
            a.setToolTip('Pan axes with left mouse, zoom with right')
            a = self.navi_toolbar.addAction(self.navi_toolbar._icon('zoom_to_rect.png'), 'Zoom',
                                            self.navi_toolbar.zoom)
            a.setToolTip('Zoom to Rectangle')
            a = self.navi_toolbar.addAction(self.navi_toolbar._icon('filesave.png'), 'Save',
                               self.navi_toolbar.save_figure)
            a.setToolTip('Save the figure')
            
            QtGui.QShortcut(QtGui.QKeySequence("Ctrl+C"),self, self.copy_to_clipboard)

            self.xcombo = QtGui.QComboBox()
            x = [':,0', ':,1', ':,2', ':,3', ':,4', ':,5', ':,6', ':,7', ':,8']
            self.xcombo.addItems(x)
            self.lbl = QtGui.QLabel('X values')
            self.lbl.setAlignment(QtCore.Qt.AlignHCenter)            
            self.toolbar_grid.addWidget(self.xcombo)
            self.toolbar_grid.addWidget(self.lbl)

            self.ycombo = QtGui.QComboBox()
            y = [':,0', ':,1', ':,2', ':,3', ':,4', ':,5', ':,6', ':,7', ':,8']
            self.ycombo.addItems(y)
            self.lbl = QtGui.QLabel('Y values')
            self.lbl.setAlignment(QtCore.Qt.AlignHCenter)            
            self.toolbar_grid.addWidget(self.ycombo)
            self.toolbar_grid.addWidget(self.lbl)
            
            self.xlabel = QtGui.QInputDialog.getText(self, 'X-axis Label')
            
            #Button_layout is a QT desginer Grid Layout.
            self.toolbar_grid.addWidget(self.navi_toolbar)
            self.Button_Definitions()
            #self.plot_options() 
            
if __name__=='__main__':
    #Creates Main UI window
    app = QtGui.QApplication(sys.argv)
    
    app.processEvents()
    
    #Creates Window Form     
    form = ArchaeoPYMainWindow()
    
    #display form and focus
    form.show()
    #if sys.platform == "darwin":
    form.raise_()
    
    #Something to do with the App & Cleanup?
    app.exec_()
    #atexit.register(form.cleanup)